# Generated by Django 2.2.13 on 2021-01-13 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('commodity', models.CharField(choices=[('food', '食物'), ('book', '书'), ('clothes', '衣服'), ('software', '软件')], default='food', max_length=100, verbose_name='商品')),
                ('remarks', models.TextField(default='null', verbose_name='备注')),
                ('status', models.CharField(choices=[('Normal', '正常'), ('Cancelled', '取消')], default='Normal', max_length=100)),
                ('cancel', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
