# Generated by Django 2.2.13 on 2021-01-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Normal', '正常')], default='Normal', max_length=100, verbose_name='状态'),
        ),
    ]
