"""
Django settings for MyDjango project.

Generated by 'django-admin startproject' using Django 2.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# 项目路径
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# 密钥
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r1(_y@0meuwt&1ska2%#&7e2gp7&sdt*)iu70xya_v$ygr%rl!'

# 调试模式
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 域名访问权限
ALLOWED_HOSTS = []

# APP 列表
# Application definition

INSTALLED_APPS = [
    # 内置的后台管理系统
    'django.contrib.admin',
    # 内置的用户登录认证
    'django.contrib.auth',
    # 所有model元数据
    'django.contrib.contenttypes',
    # 会话，表示当前访问用户的身份
    'django.contrib.sessions',
    # 消息提示
    'django.contrib.messages',
    # 静态资源路径
    'django.contrib.staticfiles',
    # 注册个人的APP
    'index',
    'douban',
]

# 中间件。中间件是 request 和 response 对象之间的钩子
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# url 配置文件
ROOT_URLCONF = 'MyDjango.urls'

# 模板配置
TEMPLATES = [
    {
        # 定义模板引擎
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 设置模板路径
        'DIRS': [],
        # 是否在 APP 里查找模板文件
        'APP_DIRS': True,
        # 用于 RequestContext 上下文的调用函数
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MyDjango.wsgi.application'

# 数据库配置。默认使用 sqlite3
# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# mysql 配置
# 安装 mysql 驱动。参考：https://docs.djangoproject.com/zh-hans/3.0/ref/databases/#mysql-notes
# pip install mysqlclient
# pip install pymysql
DATABASES = {
    'default': {
        # 数据库名称
        'NAME': 'test',
        'ENGINE': 'django.db.backends.mysql',
        'USER': 'ekpapi',
        'PASSWORD': 'P@ssw0rd',
        'HOST': '192.168.10.43',
        'PORT': '3306',
        'OPTIONS': {
            'autocommit': False,
        },
    }
    #      可能使用到的第二个数据库
    #     'db2': {
    #         'NAME': 'user_data',
    #         'ENGINE': 'mysql.connector.django',
    #         'USER': 'mysql_user',
    #         'PASSWORD': 'password',
    #         'OPTIONS': {
    #           'autocommit': True,
    #         },
    #     }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
